language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
addons:
  apt:
    packages:
    - sshpass
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -e rsync -r --delete-after --quiet public ubuntu@18.163.206.60:~/throwable.cn
  on:
    branch: master
