language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
before_deploy:
- sudo apt-get update && apt-get install sshpass  # install sshpass
deploy:
  provider: script
  cleanup: false
  script: sshpass -e scp -r public ubuntu@18.163.206.60:~/throwable.cn
  on:
    branch: master
